@isTest
public class fntsPartnerConnForward_Test {
    /* Commenting out the test class as per the Story S-46099
    public static testMethod void fnniAcctRelPortTrigger() {
        //08/08/2019 Added as part of test class fix -begin
        List<TriggerSupport__c> triggerSupportList = new List<TriggerSupport__c>();
        TriggerSupport__c accountTriggerSupportSetting = new TriggerSupport__c();
        accountTriggerSupportSetting.Name = 'Account';
        accountTriggerSupportSetting.TriggerIsDisabled__c = true;
        triggerSupportList.add(accountTriggerSupportSetting);
        insert triggerSupportList;
        
        FNNI_Account_Relationship_Portal__c insertTest = new FNNI_Account_Relationship_Portal__c(
                                                            Name__c = 'insertTest');
        
        insert insertTest;
        
    }
*/
}